import { supabase } from '@/services/supabase';
import type { BreakActivity, FocusBreak, FocusSession, FocusSubject } from '@/types/database';
import { addDays, fromDateKey } from '@/utils/dates';

function range(dateKey: string) { const start = fromDateKey(dateKey); return { start: start.toISOString(), end: addDays(start, 1).toISOString() }; }
export async function listSubjects(userId: string) { const { data, error } = await supabase.from('focus_subjects').select('*').eq('user_id', userId).order('created_at'); if (error) throw error; return data as FocusSubject[]; }
export async function addSubject(userId: string, name: string) { const { data, error } = await supabase.from('focus_subjects').insert({ user_id: userId, name }).select('*').single(); if (error) throw error; return data as FocusSubject; }
export async function deleteSubject(userId: string, subjectId: string) { const { error } = await supabase.from('focus_subjects').delete().eq('id', subjectId).eq('user_id', userId); if (error) throw error; }
export async function listSessions(userId: string, dateKey: string) { const dates = range(dateKey); const { data, error } = await supabase.from('focus_sessions').select('*').eq('user_id', userId).gte('start_time', dates.start).lt('start_time', dates.end).order('start_time'); if (error) throw error; return data as FocusSession[]; }
export async function listSessionsBetween(userId: string, start: Date, end: Date) { const { data, error } = await supabase.from('focus_sessions').select('*').eq('user_id', userId).gte('start_time', start.toISOString()).lt('start_time', end.toISOString()).order('start_time'); if (error) throw error; return data as FocusSession[]; }
export async function listBreaks(userId: string, dateKey: string) { const dates = range(dateKey); const { data, error } = await supabase.from('focus_breaks').select('*').eq('user_id', userId).gte('start_time', dates.start).lt('start_time', dates.end).order('start_time'); if (error) throw error; return data as FocusBreak[]; }
export async function saveSession(userId: string, subjectId: string, start: Date, end: Date) { const duration_seconds = Math.max(1, Math.round((end.getTime() - start.getTime()) / 1000)); const { data, error } = await supabase.from('focus_sessions').insert({ user_id: userId, subject_id: subjectId, start_time: start.toISOString(), end_time: end.toISOString(), duration_seconds }).select('*').single(); if (error) throw error; return data as FocusSession; }
export async function saveBreak(userId: string, activity: BreakActivity, note: string | null, start: Date, end: Date) { const duration_seconds = Math.max(1, Math.round((end.getTime() - start.getTime()) / 1000)); const { data, error } = await supabase.from('focus_breaks').insert({ user_id: userId, activity_type: activity, custom_note: note, start_time: start.toISOString(), end_time: end.toISOString(), duration_seconds }).select('*').single(); if (error) throw error; return data as FocusBreak; }
