import { ImagePlus, Mic, Square } from 'lucide-react-native';
import { RecordingPresets, requestRecordingPermissionsAsync, setAudioModeAsync, useAudioRecorder, useAudioRecorderState } from 'expo-audio';
import * as ImagePicker from 'expo-image-picker';
import { useState } from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { useTheme } from '@/contexts/ThemeContext';
import { AnimatedPressable } from '@/components/ui/AnimatedPressable';

export type AttachmentFile = { uri: string; mimeType: string; fileName: string; kind: 'image' | 'video' | 'audio' };

export function AttachmentBar({ onAttachment }: { onAttachment: (file: AttachmentFile) => Promise<void> }) {
  const { colors } = useTheme(); const recorder = useAudioRecorder(RecordingPresets.HIGH_QUALITY); const state = useAudioRecorderState(recorder); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  const pickImage = async () => { const permission = await ImagePicker.requestMediaLibraryPermissionsAsync(); if (!permission.granted) { setError('Photo permission is required.'); return; } const result = await ImagePicker.launchImageLibraryAsync({ mediaTypes: ['images', 'videos'], quality: 0.85 }); const asset = result.assets?.[0]; if (!asset) return; const isVideo = asset.type === 'video'; setBusy(true); try { await onAttachment({ uri: asset.uri, mimeType: asset.mimeType ?? (isVideo ? 'video/mp4' : 'image/jpeg'), fileName: asset.fileName ?? `${isVideo ? 'video' : 'photo'}-${Date.now()}.${isVideo ? 'mp4' : 'jpg'}`, kind: isVideo ? 'video' : 'image' }); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Upload failed.'); } finally { setBusy(false); } };
  const toggleRecording = async () => { setError(null); if (state.isRecording) { await recorder.stop(); if (recorder.uri) { setBusy(true); try { await onAttachment({ uri: recorder.uri, mimeType: 'audio/m4a', fileName: `recording-${Date.now()}.m4a`, kind: 'audio' }); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Audio upload failed.'); } finally { setBusy(false); } } return; } const permission = await requestRecordingPermissionsAsync(); if (!permission.granted) { setError('Microphone permission is required.'); return; } await setAudioModeAsync({ allowsRecording: true, playsInSilentMode: true }); await recorder.prepareToRecordAsync(); recorder.record(); };
  return <View><View style={styles.row}><AnimatedPressable disabled={busy} onPress={() => void pickImage()} style={[styles.button, { backgroundColor: colors.cardElevated, borderColor: colors.border }]}><ImagePlus size={17} color={colors.accent} /><Text style={[styles.label, { color: colors.text }]}>Photo / Video</Text></AnimatedPressable><AnimatedPressable disabled={busy} onPress={() => void toggleRecording()} style={[styles.button, { backgroundColor: state.isRecording ? colors.danger : colors.cardElevated, borderColor: colors.border }]}>{state.isRecording ? <Square size={15} color="#FFF" fill="#FFF" /> : <Mic size={17} color={colors.accent} />}<Text style={[styles.label, { color: state.isRecording ? '#FFF' : colors.text }]}>{state.isRecording ? 'Stop recording' : 'Record audio'}</Text></AnimatedPressable>{busy && <Text style={{ color: colors.textMuted, fontSize: 11 }}>Uploading…</Text>}</View>{error && <Text style={{ color: colors.danger, fontSize: 11, marginTop: 5 }}>{error}</Text>}</View>;
}
const styles = StyleSheet.create({ row: { flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap', gap: 8 }, button: { minHeight: 38, borderRadius: 13, borderWidth: StyleSheet.hairlineWidth, paddingHorizontal: 11, flexDirection: 'row', alignItems: 'center', gap: 6 }, label: { fontSize: 11, fontWeight: '800' } });
