import { BookOpen, Folder, FolderPlus, Grid2X2, List, LockKeyhole, NotebookPen, Plus, Search, Trash2 } from 'lucide-react-native';
import { useCallback, useMemo, useState } from 'react';
import { useFocusEffect, useRouter } from 'expo-router';
import { Alert, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { JournalCard } from '@/components/journal/JournalCard';
import { JournalComposer } from '@/components/journal/JournalComposer';
import { MomentsCarousel } from '@/components/journal/MomentsCarousel';
import { useFloatingTabBarMetrics } from '@/components/navigation/FloatingTabBar';
import { NoteCard } from '@/components/notes/NoteCard';
import { NoteEditorModal } from '@/components/notes/NoteEditorModal';
import { AppModal } from '@/components/ui/AppModal';
import { AnimatedPressable } from '@/components/ui/AnimatedPressable';
import { Button } from '@/components/ui/Button';
import { FormInput } from '@/components/ui/FormInput';
import { Screen } from '@/components/ui/Screen';
import { SlidingSegmentedControl } from '@/components/ui/SlidingSegmentedControl';
import { useAuth } from '@/contexts/AuthContext';
import { useTheme } from '@/contexts/ThemeContext';
import { useJournal } from '@/hooks/useJournal';
import { NotesScope, useNotes } from '@/hooks/useNotes';
import { uploadAttachment } from '@/services/notes';
import type { JournalEntry, Note } from '@/types/database';
import { verifyPin } from '@/utils/pinSecurity';

type Section = 'notes' | 'journal';
export function NotesJournalScreen() {
  const { colors } = useTheme(); const { user } = useAuth(); const router = useRouter(); const [section, setSection] = useState<Section>('notes'); const [search, setSearch] = useState('');
  const { actionBottom, contentBottom } = useFloatingTabBarMetrics();
  const [scope, setScope] = useState<NotesScope>({ kind: 'all' }); const [grid, setGrid] = useState(false); const notes = useNotes(scope, section === 'notes' ? search : ''); const journal = useJournal(section === 'journal' ? search : '');
  const refreshNotes = notes.refresh;
  const [editorOpen, setEditorOpen] = useState(false); const [editingNote, setEditingNote] = useState<Note | null>(null); const [folderModal, setFolderModal] = useState(false); const [folderName, setFolderName] = useState(''); const [moveNote, setMoveNote] = useState<Note | null>(null); const [lockedNote, setLockedNote] = useState<Note | null>(null); const [pin, setPin] = useState(''); const [message, setMessage] = useState<string | null>(null);
  const [composerOpen, setComposerOpen] = useState(false); const [editingEntry, setEditingEntry] = useState<JournalEntry | null>(null); const [moment, setMoment] = useState<{ category: string; prompt: string } | null>(null);
  const openNote = (note: Note) => { if (note.is_locked) { setLockedNote(note); setPin(''); return; } setEditingNote(note); setEditorOpen(true); };
  const upload = async (file: { uri: string; mimeType: string; fileName: string; kind: 'image' | 'video' | 'audio' }, area: 'notes' | 'journal') => { if (!user) throw new Error('Sign in to upload.'); const result = await uploadAttachment(user.id, file.uri, file.mimeType, file.fileName, area); return { id: `${Date.now()}`, kind: file.kind, url: result.signedUrl, path: result.path, name: file.fileName } as const; };
  const pinned = notes.notes.filter((note) => note.is_pinned); const standard = notes.notes.filter((note) => !note.is_pinned);
  const folderId = scope.kind === 'folder' ? scope.id : null;
  const groups = useMemo(() => { const map = new Map<string, JournalEntry[]>(); for (const entry of journal.entries) map.set(entry.date_string, [...(map.get(entry.date_string) ?? []), entry]); return [...map.entries()]; }, [journal.entries]);
  const scopeOptions: { key: string; label: string; value: NotesScope; icon?: typeof Folder }[] = [{ key: 'all', label: 'All Notes', value: { kind: 'all' } }, { key: 'quick', label: 'Quick Notes', value: { kind: 'quick' } }, ...notes.folders.map((item) => ({ key: item.id, label: item.name, value: { kind: 'folder' as const, id: item.id }, icon: Folder })), { key: 'deleted', label: 'Recently Deleted', value: { kind: 'deleted' }, icon: Trash2 }];
  const scopeKey = scope.kind === 'folder' ? scope.id : scope.kind;
  const confirmTrash = (note: Note) => { if (scope.kind !== 'deleted') { void notes.trashNote(note.id); return; } Alert.alert('Delete permanently?', 'This note cannot be recovered.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Delete', style: 'destructive', onPress: () => void notes.permanentlyDelete(note.id) }]); };
  useFocusEffect(useCallback(() => { if (section === 'notes') void refreshNotes(); }, [section, refreshNotes]));

  return <Screen contentStyle={[styles.screen, { paddingBottom: contentBottom }]}> 
    <SlidingSegmentedControl<Section>
      value={section}
      options={[{ value: 'notes', label: 'Notes', icon: NotebookPen }, { value: 'journal', label: 'Journal', icon: BookOpen }]}
      activeColor={section === 'notes' ? colors.notesAccent : colors.journalAccent}
      activeTextColor={section === 'notes' ? '#09090B' : colors.buttonText}
      onChange={(value) => { setSection(value); setSearch(''); }}
    />
    <View style={styles.header}><View><Text style={[styles.title, { color: colors.text }]}>{section === 'notes' ? 'Notes' : 'Journal'}</Text><Text style={[styles.subtitle, { color: colors.textMuted }]}>{section === 'notes' ? 'Capture ideas, lists, and details.' : 'Your life, one moment at a time.'}</Text></View>{section === 'notes' && <View style={styles.viewToggle}><AnimatedPressable onPress={() => setGrid(false)} style={[styles.viewButton, !grid && { backgroundColor: colors.cardElevated }]}><List size={18} color={!grid ? colors.notesAccent : colors.textMuted} /></AnimatedPressable><AnimatedPressable onPress={() => setGrid(true)} style={[styles.viewButton, grid && { backgroundColor: colors.cardElevated }]}><Grid2X2 size={17} color={grid ? colors.notesAccent : colors.textMuted} /></AnimatedPressable></View>}</View>
    <View style={[styles.search, { backgroundColor: colors.card, borderColor: colors.border }]}><Search size={17} color={colors.textMuted} /><TextInput value={search} onChangeText={setSearch} placeholder={`Search ${section}`} placeholderTextColor={colors.textMuted} style={[styles.searchInput, { color: colors.text }]} /></View>
    {section === 'notes' ? <>
      <View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.folders}>{scopeOptions.map((item) => <AnimatedPressable key={item.key} onPress={() => setScope(item.value)} style={[styles.folder, { backgroundColor: scopeKey === item.key ? `${colors.notesAccent}24` : colors.card, borderColor: scopeKey === item.key ? colors.notesAccent : colors.border }]}>{item.icon && <item.icon size={13} color={scopeKey === item.key ? colors.notesAccent : colors.textMuted} />}<Text style={[styles.folderText, { color: colors.text }]}>{item.label}</Text></AnimatedPressable>)}<AnimatedPressable onPress={() => setFolderModal(true)} style={[styles.folder, { borderColor: colors.border }]}><FolderPlus size={14} color={colors.notesAccent} /><Text style={[styles.folderText, { color: colors.text }]}>New Folder</Text></AnimatedPressable></ScrollView></View>
      <ScrollView style={styles.feed} contentContainerStyle={styles.feedContent}>{notes.loading && <Text style={{ color: colors.textMuted }}>Loading notes…</Text>}{pinned.length > 0 && <View style={styles.noteSection}><Text style={[styles.sectionLabel, { color: colors.textMuted }]}>PINNED</Text><View style={grid ? styles.grid : undefined}>{pinned.map((note, index) => <NoteCard key={note.id} index={index} note={note} grid={grid} deleted={scope.kind === 'deleted'} onOpen={() => openNote(note)} onPin={() => void notes.togglePinned(note)} onMove={() => setMoveNote(note)} onTrash={() => confirmTrash(note)} onRestore={() => void notes.restoreNote(note.id)} />)}</View></View>}<View style={styles.noteSection}><Text style={[styles.sectionLabel, { color: colors.textMuted }]}>{scope.kind === 'deleted' ? 'RECENTLY DELETED' : 'NOTES'}</Text><View style={grid ? styles.grid : undefined}>{standard.map((note, index) => <NoteCard key={note.id} index={pinned.length + index} note={note} grid={grid} deleted={scope.kind === 'deleted'} onOpen={() => openNote(note)} onPin={() => void notes.togglePinned(note)} onMove={() => setMoveNote(note)} onTrash={() => confirmTrash(note)} onRestore={() => void notes.restoreNote(note.id)} />)}</View>{!notes.loading && notes.notes.length === 0 && <Text style={[styles.empty, { color: colors.textMuted }]}>No notes in this folder.</Text>}</View>{notes.error && <Text style={{ color: colors.danger }}>{notes.error}</Text>}</ScrollView>
      {scope.kind !== 'deleted' && <AnimatedPressable accessibilityLabel="New note" onPress={() => router.push({ pathname: '/notes/new', params: folderId ? { folderId } : {} })} style={[styles.fab, { bottom: actionBottom, backgroundColor: colors.notesAccent }]}><Plus size={25} color="#000" /></AnimatedPressable>}
    </> : <>
      <MomentsCarousel onSelect={(category, prompt) => { setMoment({ category, prompt }); setEditingEntry(null); setComposerOpen(true); }} />
      <ScrollView style={styles.feed} contentContainerStyle={styles.journalFeed}>{groups.map(([date, entries]) => <View key={date} style={styles.dayGroup}><Text style={[styles.dateHeader, { color: colors.text }]}>{new Date(`${date}T12:00:00`).toLocaleDateString(undefined, { weekday: 'long', month: 'long', day: 'numeric' })}</Text>{entries.map((entry, index) => <JournalCard key={entry.id} index={index} entry={entry} onOpen={() => { setEditingEntry(entry); setMoment(null); setComposerOpen(true); }} onBookmark={() => void journal.toggleBookmark(entry)} onDelete={() => Alert.alert('Delete journal entry?', entry.title || 'Untitled moment', [{ text: 'Cancel', style: 'cancel' }, { text: 'Delete', style: 'destructive', onPress: () => void journal.deleteEntry(entry.id) }])} />)}</View>)}{!journal.loading && journal.entries.length === 0 && <Text style={[styles.empty, { color: colors.textMuted }]}>Your first moment starts here.</Text>}{journal.error && <Text style={{ color: colors.danger }}>{journal.error}</Text>}</ScrollView><AnimatedPressable accessibilityLabel="New journal entry" onPress={() => { setEditingEntry(null); setMoment(null); setComposerOpen(true); }} style={[styles.fab, { bottom: actionBottom, backgroundColor: colors.journalAccent }]}><Plus size={25} color={colors.buttonText} /></AnimatedPressable>
    </>}
    {message && <Text style={[styles.message, { color: colors.danger }]}>{message}</Text>}
    <NoteEditorModal note={editingNote} visible={editorOpen} folderId={folderId} onClose={() => setEditorOpen(false)} onSave={notes.saveNote} onUpload={(file) => upload(file, 'notes')} />
    <JournalComposer visible={composerOpen} entry={editingEntry} initialPrompt={moment} onClose={() => setComposerOpen(false)} onSave={journal.saveEntry} onUpload={async (file) => { const item = await upload(file, 'journal'); return { url: item.url, kind: file.kind }; }} />
    <AppModal visible={folderModal} onClose={() => setFolderModal(false)}><View style={styles.modal}><Text style={[styles.modalTitle, { color: colors.text }]}>New Folder</Text><FormInput accessibilityLabel="Folder name" value={folderName} onChangeText={setFolderName} placeholder="Folder name" autoFocus /><Button label="Create" disabled={!folderName.trim()} onPress={() => void notes.createFolder(folderName.trim()).then(() => { setFolderName(''); setFolderModal(false); })} /></View></AppModal>
    <AppModal visible={Boolean(moveNote)} onClose={() => setMoveNote(null)}><View style={styles.modal}><Text style={[styles.modalTitle, { color: colors.text }]}>Move Note</Text><Button label="Quick Notes" variant="secondary" onPress={() => { if (!moveNote) return; void notes.moveNote(moveNote.id, null).then(() => setMoveNote(null)); }} />{notes.folders.map((folder) => <Button key={folder.id} label={folder.name} variant="secondary" onPress={() => { if (!moveNote) return; void notes.moveNote(moveNote.id, folder.id).then(() => setMoveNote(null)); }} />)}</View></AppModal>
    <AppModal visible={Boolean(lockedNote)} onClose={() => setLockedNote(null)}><View style={styles.modal}><LockKeyhole size={26} color={colors.notesAccent} /><Text style={[styles.modalTitle, { color: colors.text }]}>Unlock Note</Text><FormInput accessibilityLabel="Note PIN" value={pin} onChangeText={setPin} secureTextEntry placeholder="PIN or password" /><Button label="Unlock" onPress={() => { if (!lockedNote?.pin_hash) return; void verifyPin(pin, lockedNote.pin_hash).then((valid) => { if (!valid) { setMessage('Incorrect note PIN.'); return; } const note = lockedNote; setLockedNote(null); setEditingNote(note); setEditorOpen(true); }); }} /></View></AppModal>
  </Screen>;
}

const styles = StyleSheet.create({ screen: { paddingTop: 12, paddingBottom: 94, gap: 11 }, header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, title: { fontSize: 30, fontWeight: '800' }, subtitle: { fontSize: 11, marginTop: 1 }, viewToggle: { flexDirection: 'row', gap: 3 }, viewButton: { width: 37, height: 34, borderRadius: 10, alignItems: 'center', justifyContent: 'center' }, search: { minHeight: 43, borderRadius: 13, borderWidth: StyleSheet.hairlineWidth, paddingHorizontal: 12, flexDirection: 'row', alignItems: 'center', gap: 8 }, searchInput: { flex: 1, fontSize: 13 }, folders: { gap: 7 }, folder: { minHeight: 35, borderRadius: 12, borderWidth: StyleSheet.hairlineWidth, paddingHorizontal: 10, flexDirection: 'row', alignItems: 'center', gap: 5 }, folderText: { fontSize: 10, fontWeight: '700' }, feed: { flex: 1 }, feedContent: { paddingBottom: 70 }, noteSection: { marginBottom: 14 }, sectionLabel: { fontSize: 9, fontWeight: '800', letterSpacing: 1, marginBottom: 5 }, grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 9 }, empty: { textAlign: 'center', paddingVertical: 36, fontSize: 12 }, fab: { position: 'absolute', right: 22, bottom: 98, width: 52, height: 52, borderRadius: 26, alignItems: 'center', justifyContent: 'center', shadowColor: '#000', shadowOpacity: 0.2, shadowRadius: 12, shadowOffset: { width: 0, height: 6 }, elevation: 6 }, journalFeed: { gap: 17, paddingBottom: 74 }, dayGroup: { gap: 10 }, dateHeader: { fontSize: 15, fontWeight: '700' }, modal: { gap: 12 }, modalTitle: { fontSize: 22, fontWeight: '800' }, message: { position: 'absolute', bottom: 90, left: 20, fontSize: 11 } });
