import { Check } from 'lucide-react-native';
import { useEffect, useState } from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { AppModal } from '@/components/ui/AppModal';
import { AnimatedPressable } from '@/components/ui/AnimatedPressable';
import { Button } from '@/components/ui/Button';
import { FormInput } from '@/components/ui/FormInput';
import { ValidationFeedback } from '@/components/ui/ValidationFeedback';
import { useTheme } from '@/contexts/ThemeContext';
import type { Habit, HabitInput } from '@/types/database';

const days = ['S', 'M', 'T', 'W', 'T', 'F', 'S'];
const emojiChoices = ['📚', '🏃', '🧘', '💧', '💪', '🎯', '🌱', '✨'];
export function HabitFormModal({ visible, habit, onClose, onCreate, onUpdate }: { visible: boolean; habit?: Habit | null; onClose: () => void; onCreate: (input: HabitInput) => Promise<void>; onUpdate?: (habitId: string, input: HabitInput) => Promise<void> }) {
  const { colors } = useTheme(); const [title, setTitle] = useState(''); const [emoji, setEmoji] = useState(''); const [selected, setSelected] = useState<number[]>([1,2,3,4,5]); const [time, setTime] = useState(''); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);
  const [errorPulse, setErrorPulse] = useState(0); const fail = (message: string) => { setError(message); setErrorPulse((current) => current + 1); };
  useEffect(() => { if (visible) { setTitle(typeof habit?.title === 'string' ? habit.title : ''); setEmoji(typeof habit?.emoji === 'string' ? habit.emoji : ''); setSelected(Array.isArray(habit?.days_of_week) ? [...habit.days_of_week] : [1,2,3,4,5]); setTime(typeof habit?.time === 'string' ? habit.time.slice(0, 5) : ''); setError(null); } }, [visible, habit]);
  const submit = async () => { if (!title.trim() || !selected.length) { fail('Add a title and choose at least one day.'); return; } if (time && !/^([01]\d|2[0-3]):[0-5]\d$/.test(time)) { fail('Use 24-hour time, for example 08:30.'); return; } setSaving(true); const input: HabitInput = { title: title.trim(), emoji: emoji.trim() || null, daysOfWeek: selected, time: time || null }; try { if (habit && onUpdate) await onUpdate(habit.id, input); else await onCreate(input); onClose(); } catch (cause) { fail(cause instanceof Error ? cause.message : `Unable to ${habit ? 'update' : 'add'} habit.`); } finally { setSaving(false); } };
  const close = () => { if (!saving) onClose(); };
  return <AppModal visible={visible} onClose={close}><ValidationFeedback trigger={errorPulse}><View style={styles.content}><Text style={[styles.title, { color: colors.text }]}>{habit ? 'Edit habit' : 'New habit'}</Text><FormInput accessibilityLabel="Habit title" value={title} onChangeText={setTitle} placeholder="Read, walk, meditate…" autoFocus /><Text style={[styles.label, { color: colors.textMuted }]}>CHOOSE AN EMOJI</Text><View style={styles.emojis}>{emojiChoices.map((choice) => { const active = emoji === choice; return <AnimatedPressable key={choice} accessibilityRole="radio" accessibilityState={{ selected: active }} accessibilityLabel={`Use ${choice} for this habit`} onPress={() => setEmoji(active ? '' : choice)} style={[styles.emojiChoice, { backgroundColor: active ? colors.accentSoft : colors.card, borderColor: active ? colors.accent : colors.border }]}><Text style={styles.emojiText}>{choice}</Text></AnimatedPressable>; })}</View><FormInput accessibilityLabel="Custom emoji (optional)" value={emoji} onChangeText={setEmoji} placeholder="Type or paste an emoji" maxLength={16} /><Text style={[styles.label, { color: colors.textMuted }]}>REPEAT ON</Text><View style={styles.days}>{days.map((day, index) => { const active = selected.includes(index); return <AnimatedPressable key={index} accessibilityRole="checkbox" accessibilityState={{ checked: active }} onPress={() => setSelected((current) => active ? current.filter((value) => value !== index) : [...current, index])} style={[styles.day, { backgroundColor: active ? colors.accent : colors.card, borderColor: active ? colors.accent : colors.border }]}>{active ? <Check size={14} color={colors.buttonText} /> : <Text style={[styles.dayText, { color: colors.text }]}>{day}</Text>}</AnimatedPressable>; })}</View><FormInput accessibilityLabel="Optional time" value={time} onChangeText={setTime} placeholder="Optional time · HH:MM" keyboardType="numbers-and-punctuation" />{error && <Text style={{ color: colors.danger, fontSize: 11 }}>{error}</Text>}<View style={styles.actions}><Button label="Cancel" variant="secondary" disabled={saving} onPress={close} style={styles.action} /><Button label={habit ? 'Save changes' : 'Add habit'} loading={saving} onPress={() => void submit()} style={styles.action} /></View></View></ValidationFeedback></AppModal>;
}
const styles = StyleSheet.create({ content: { gap: 14 }, title: { fontSize: 25, fontWeight: '800' }, label: { fontSize: 10, fontWeight: '800', letterSpacing: 1 }, emojis: { flexDirection: 'row', flexWrap: 'wrap', gap: 7 }, emojiChoice: { width: 38, height: 38, borderRadius: 13, borderWidth: StyleSheet.hairlineWidth, alignItems: 'center', justifyContent: 'center' }, emojiText: { fontSize: 20, lineHeight: 25 }, days: { flexDirection: 'row', justifyContent: 'space-between' }, day: { width: 38, height: 38, borderRadius: 19, borderWidth: StyleSheet.hairlineWidth, alignItems: 'center', justifyContent: 'center' }, dayText: { fontSize: 12, fontWeight: '700' }, actions: { flexDirection: 'row', gap: 8 }, action: { flex: 1 } });
