import { Flame } from 'lucide-react-native';
import { StyleSheet, Text, View } from 'react-native';
import { AnimatedPressable } from '@/components/ui/AnimatedPressable';
import { Checkbox } from '@/components/ui/Checkbox';
import { useTheme } from '@/contexts/ThemeContext';
import type { HabitWithLogs } from '@/types/database';

export function HabitRow({ habit, onToggle, onPress }: { habit: HabitWithLogs; onToggle: () => void; onPress: () => void }) { const { colors } = useTheme(); return <AnimatedPressable accessibilityRole="button" accessibilityLabel={`Open options for ${habit.title}`} onPress={onPress} style={[styles.row, { borderBottomColor: colors.border }]}><Checkbox checked={habit.completedOnSelectedDate} onPress={onToggle} label={`${habit.completedOnSelectedDate ? 'Uncomplete' : 'Complete'} ${habit.title}`} />{habit.emoji ? <View style={[styles.emoji, { backgroundColor: colors.cardElevated, borderColor: colors.border }]}><Text style={styles.emojiText}>{habit.emoji}</Text></View> : null}<View style={styles.copy}><Text style={[styles.title, { color: colors.text, textDecorationLine: habit.completedOnSelectedDate ? 'line-through' : 'none' }]}>{habit.title}</Text><Text style={[styles.time, { color: colors.textMuted }]}>{habit.time ? habit.time.slice(0, 5) : 'Any time'}</Text></View><Flame size={16} color={habit.streak ? '#FF9F0A' : colors.textMuted} /><Text style={[styles.streak, { color: colors.text }]}>{habit.streak}</Text></AnimatedPressable>; }
const styles = StyleSheet.create({ row: { minHeight: 58, borderBottomWidth: StyleSheet.hairlineWidth, flexDirection: 'row', alignItems: 'center', gap: 10 }, emoji: { width: 34, height: 34, borderRadius: 12, borderWidth: StyleSheet.hairlineWidth, alignItems: 'center', justifyContent: 'center' }, emojiText: { fontSize: 18, lineHeight: 23 }, copy: { flex: 1, minWidth: 0 }, title: { fontSize: 14, fontWeight: '600' }, time: { fontSize: 10, marginTop: 3 }, streak: { width: 20, fontSize: 12, fontWeight: '800' } });
