import { CalendarPlus, GripVertical, RefreshCw } from 'lucide-react-native';
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { Animated, PanResponder, ScrollView, StyleSheet, Text, View } from 'react-native';
import { CalendarGrid } from '@/components/calendar/CalendarGrid';
import { HabitFormModal } from '@/components/habits/HabitFormModal';
import { HabitRow } from '@/components/habits/HabitRow';
import { AppModal } from '@/components/ui/AppModal';
import { AnimatedPressable } from '@/components/ui/AnimatedPressable';
import { Button } from '@/components/ui/Button';
import { FormInput } from '@/components/ui/FormInput';
import { Screen } from '@/components/ui/Screen';
import { SlidingSegmentedControl } from '@/components/ui/SlidingSegmentedControl';
import { useAuth } from '@/contexts/AuthContext';
import { useCalendar } from '@/contexts/CalendarContext';
import { useTheme } from '@/contexts/ThemeContext';
import { useHabits } from '@/hooks/useHabits';
import { priorityColors } from '@/constants/theme';
import { listTasksInRange } from '@/services/tasks';
import type { HabitWithLogs, Task } from '@/types/database';
import type { GoogleCalendarEvent } from '@/types/calendar';
import { formatEventTime, fromDateKey, toDateKey } from '@/utils/dates';

function ScheduleDrag({ onDrop, color }: { onDrop: (hour: number) => void; color: string }) {
  const [y] = useState(() => new Animated.Value(0));
  const pan = useMemo(() => PanResponder.create({ onStartShouldSetPanResponder: () => true, onMoveShouldSetPanResponder: () => true, onPanResponderMove: Animated.event([null, { dy: y }], { useNativeDriver: false }), onPanResponderRelease: (_event, gesture) => { const hour = Math.max(6, Math.min(22, 8 + Math.round(gesture.dy / 38))); y.setValue(0); onDrop(hour); }, onPanResponderTerminate: () => y.setValue(0) }), [onDrop, y]);
  return <Animated.View {...pan.panHandlers} style={[styles.dragSeed, { backgroundColor: color, transform: [{ translateY: y }] }]}><GripVertical color="#FFF" size={16} /><Text style={styles.dragText}>Drag new event into a time slot</Text></Animated.View>;
}

function eventDateAt(dateKey: string, clock: string) {
  const dateParts = /^(\d{4})-(\d{2})-(\d{2})$/.exec(dateKey);
  const timeParts = /^(\d{1,2}):(\d{2})$/.exec(clock.trim());
  if (!dateParts || !timeParts) return null;
  const year = Number(dateParts[1]); const month = Number(dateParts[2]); const day = Number(dateParts[3]); const hour = Number(timeParts[1]); const minute = Number(timeParts[2]);
  if ([year, month, day, hour, minute].some(Number.isNaN) || month < 1 || month > 12 || day < 1 || day > 31 || hour < 0 || hour > 23 || minute < 0 || minute > 59) return null;
  const result = new Date(year, month - 1, day, hour, minute, 0, 0);
  return result.getFullYear() === year && result.getMonth() === month - 1 && result.getDate() === day ? result : null;
}

function eventClock(date: Date) {
  if (!(date instanceof Date) || Number.isNaN(date.getTime())) return '09:00';
  return `${String(date.getHours()).padStart(2, '0')}:${String(date.getMinutes()).padStart(2, '0')}`;
}

export default function CalendarScreen() {
  const { colors } = useTheme(); const { user } = useAuth(); const calendar = useCalendar(); const { connected, refresh } = calendar; const [month, setMonth] = useState(new Date()); const [selected, setSelected] = useState(toDateKey(new Date())); const [tasks, setTasks] = useState<Task[]>([]); const [tab, setTab] = useState<'events' | 'habits'>('events'); const [habitModal, setHabitModal] = useState(false); const [habitActions, setHabitActions] = useState<HabitWithLogs | null>(null); const [editingHabit, setEditingHabit] = useState<HabitWithLogs | null>(null); const [eventActions, setEventActions] = useState<GoogleCalendarEvent | null>(null); const [editingEvent, setEditingEvent] = useState<GoogleCalendarEvent | null>(null); const [eventModal, setEventModal] = useState(false); const [eventTitle, setEventTitle] = useState(''); const [startTime, setStartTime] = useState('09:00'); const [endTime, setEndTime] = useState('10:00'); const [eventError, setEventError] = useState<string | null>(null); const [actionError, setActionError] = useState<string | null>(null); const [saving, setSaving] = useState(false); const modalTransitionTimer = useRef<ReturnType<typeof setTimeout> | null>(null); const habits = useHabits(selected);
  const loadTasks = useCallback(async () => { if (!user) return; const start = toDateKey(new Date(month.getFullYear(), month.getMonth(), 1)); const end = toDateKey(new Date(month.getFullYear(), month.getMonth() + 1, 0)); try { setTasks(await listTasksInRange(user.id, start, end)); } catch { setTasks([]); } }, [user, month]);
  useEffect(() => { void loadTasks(); const from = new Date(month.getFullYear(), month.getMonth(), 1); const to = new Date(month.getFullYear(), month.getMonth() + 1, 1); if (connected) void refresh(from, to); }, [month, loadTasks, connected, refresh]);
  const dayEvents = useMemo(() => calendar.events.filter((event) => toDateKey(event.start) === selected), [calendar.events, selected]); const dayTasks = tasks.filter((task) => task.date === selected);
  useEffect(() => () => { if (modalTransitionTimer.current) clearTimeout(modalTransitionTimer.current); }, []);
  const openEventComposer = useCallback(() => { setEditingEvent(null); setEventTitle(''); setStartTime('09:00'); setEndTime('10:00'); setEventError(null); setEventModal(true); }, []);
  const openAtHour = useCallback((hour: number) => { setEditingEvent(null); setEventTitle(''); setStartTime(`${String(hour).padStart(2, '0')}:00`); setEndTime(`${String(Math.min(23, hour + 1)).padStart(2, '0')}:00`); setEventError(null); setEventModal(true); }, []);
  const openEventEditor = (event: GoogleCalendarEvent | null) => { if (!event?.id) { setEventError('This event cannot be edited because its Google event ID is missing.'); setEventActions(null); return; } setEventActions(null); if (modalTransitionTimer.current) clearTimeout(modalTransitionTimer.current); modalTransitionTimer.current = setTimeout(() => { setEditingEvent(event); setEventTitle(event.title ?? ''); setStartTime(eventClock(event.start)); setEndTime(eventClock(event.end)); setEventError(null); setEventModal(true); }, 260); };
  const openHabitEditor = (habit: HabitWithLogs | null) => { if (!habit?.id) { setHabitActions(null); return; } const currentHabit = { ...habit, days_of_week: Array.isArray(habit.days_of_week) ? [...habit.days_of_week] : [], logs: Array.isArray(habit.logs) ? [...habit.logs] : [] }; setHabitActions(null); if (modalTransitionTimer.current) clearTimeout(modalTransitionTimer.current); modalTransitionTimer.current = setTimeout(() => { setEditingHabit(currentHabit); setHabitModal(true); }, 260); };
  const saveEvent = async () => { const start = eventDateAt(selected, startTime); const end = eventDateAt(selected, endTime); if (!eventTitle.trim() || !start || !end || end <= start) { setEventError('Enter a title and valid end time after the start time. Use HH:MM, for example 09:00.'); return; } setSaving(true); setEventError(null); try { const input = { title: eventTitle.trim(), start, end }; if (editingEvent?.id) await calendar.updateEvent(editingEvent.id, input); else await calendar.addEvent(input); setEventTitle(''); setEditingEvent(null); setEventModal(false); } catch (cause) { setEventError(cause instanceof Error ? cause.message : `Unable to ${editingEvent ? 'update' : 'create'} event.`); } finally { setSaving(false); } };
  const removeEvent = async (event: GoogleCalendarEvent | null) => { if (!event?.id || saving) return; setSaving(true); setEventError(null); try { await calendar.deleteEvent(event.id); setEventActions(null); setEditingEvent(null); setEventModal(false); } catch (cause) { setEventError(cause instanceof Error ? cause.message : 'Unable to delete the event.'); } finally { setSaving(false); } };
  return <Screen scroll contentStyle={styles.screen}><View style={styles.titleRow}><View><Text style={[styles.title, { color: colors.text }]}>Calendar</Text><Text style={[styles.subtitle, { color: colors.textMuted }]}>Events first. Tasks second.</Text></View>{connected && <AnimatedPressable accessibilityLabel="Refresh" onPress={() => void refresh()} style={[styles.iconButton, { backgroundColor: colors.card }]}><RefreshCw color={colors.accent} size={19} /></AnimatedPressable>}</View>
    {!connected && <View style={[styles.connect, { backgroundColor: colors.accentSoft, borderColor: colors.border }]}><Text style={[styles.boxTitle, { color: colors.text }]}>Connect Google Calendar</Text><Text style={[styles.boxMeta, { color: colors.textMuted }]}>Event access is required to read and create events.</Text><Button label="Connect" onPress={() => void calendar.connect()} /></View>}
    {(calendar.error || actionError) && <Text style={{ color: colors.danger }}>{actionError ?? calendar.error}</Text>}
    <SlidingSegmentedControl value={tab} onChange={setTab} options={[{ value: 'events', label: 'Events' }, { value: 'habits', label: 'Habits' }]} />
    {tab === 'events' ? <View style={[styles.box, { backgroundColor: colors.card, borderColor: colors.border }]}><View style={styles.boxHeader}><View><Text style={[styles.boxTitle, { color: colors.text }]}>Events</Text><Text style={[styles.boxMeta, { color: colors.textMuted }]}>{fromDateKey(selected).toLocaleDateString(undefined, { weekday: 'long', month: 'long', day: 'numeric' })}</Text></View><Button label="Add Event" icon={CalendarPlus} onPress={openEventComposer} /></View>
      {connected && <ScheduleDrag color={colors.accent} onDrop={openAtHour} />}
      <ScrollView style={styles.eventList}>{dayEvents.length === 0 && <Text style={[styles.empty, { color: colors.textMuted }]}>No events scheduled.</Text>}{dayEvents.map((event) => <AnimatedPressable accessibilityRole="button" accessibilityLabel={`Open options for ${event.title}`} key={event.id} onPress={() => { setEventError(null); setEventActions(event); }} style={[styles.item, styles.eventItem, { backgroundColor: colors.cardElevated, borderColor: colors.border, borderLeftColor: colors.accent }]}><View style={styles.eventCopy}><Text numberOfLines={1} style={[styles.itemTitle, { color: colors.text }]}>{event.title}</Text><Text style={[styles.itemMeta, { color: colors.textMuted }]}>{formatEventTime(event.start, event.end, event.isAllDay)}</Text></View><Text style={[styles.eventHint, { color: colors.textMuted }]}>Edit</Text></AnimatedPressable>)}</ScrollView>
      <View style={styles.timeSlots}>{[8,10,12,14,16,18,20].map((hour) => <AnimatedPressable key={hour} onLongPress={() => openAtHour(hour)} style={[styles.slot, { borderTopColor: colors.border }]}><Text style={[styles.slotTime, { color: colors.textMuted }]}>{String(hour).padStart(2, '0')}:00</Text><Text style={[styles.slotHint, { color: colors.textMuted }]}>Long press to schedule</Text></AnimatedPressable>)}</View>
    </View> : <View style={[styles.box, { backgroundColor: colors.card, borderColor: colors.border }]}><View style={styles.boxHeader}><View><Text style={[styles.boxTitle, { color: colors.text }]}>Habits</Text><Text style={[styles.boxMeta, { color: colors.textMuted }]}>Scheduled for {fromDateKey(selected).toLocaleDateString(undefined, { weekday: 'long' })}</Text></View><Button label="Add Habit" icon={CalendarPlus} onPress={() => { setEditingHabit(null); setHabitModal(true); }} /></View>{habits.loading && <Text style={{ color: colors.textMuted }}>Loading habits…</Text>}{habits.habits.map((habit) => <HabitRow key={habit.id} habit={habit} onToggle={() => void habits.toggleHabit(habit)} onPress={() => setHabitActions(habit)} />)}{!habits.loading && habits.habits.length === 0 && <Text style={[styles.empty, { color: colors.textMuted }]}>No habits scheduled for this day.</Text>}{habits.error && <Text style={{ color: colors.danger }}>{habits.error}</Text>}{habits.calendarMessage && <Text style={{ color: colors.textMuted, fontSize: 11 }}>{habits.calendarMessage}</Text>}</View>}
    <CalendarGrid month={month} selected={selected} events={calendar.events} tasks={tasks} onMonthChange={(value) => { setMonth(value); setSelected(toDateKey(value)); }} onSelect={setSelected} />
    <View style={[styles.box, { backgroundColor: colors.card, borderColor: colors.border }]}><Text style={[styles.boxTitle, { color: colors.text }]}>Tasks</Text><Text style={[styles.boxMeta, { color: colors.textMuted }]}>Pending and completed tasks for the selected day.</Text>{dayTasks.length === 0 && <Text style={[styles.empty, { color: colors.textMuted }]}>No tasks for this day.</Text>}{dayTasks.map((task) => <View key={task.id} style={[styles.item, styles.taskItem, { backgroundColor: colors.cardElevated, opacity: task.is_completed ? 0.5 : 1 }]}><View style={[styles.priorityDot, { backgroundColor: priorityColors[task.priority] }]} /><Text style={[styles.itemTitle, { color: colors.text, textDecorationLine: task.is_completed ? 'line-through' : 'none' }]}>{task.title}</Text>{task.is_completed && <Text style={[styles.itemMeta, { color: colors.textMuted }]}>Completed</Text>}</View>)}</View>
    <HabitFormModal visible={habitModal} habit={editingHabit} onClose={() => { setHabitModal(false); setEditingHabit(null); }} onCreate={habits.addHabit} onUpdate={habits.editHabit} />
    <AppModal visible={Boolean(habitActions)} onClose={() => setHabitActions(null)}><View style={styles.modal}><Text style={[styles.modalTitle, { color: colors.text }]}>{habitActions?.title ?? 'Habit options'}</Text><Button label="Edit" variant="secondary" onPress={() => openHabitEditor(habitActions)} /><Button label="Delete" variant="danger" onPress={() => { const habitId = habitActions?.id; if (!habitId) return; setActionError(null); setHabitActions(null); void habits.deleteHabit(habitId).catch((cause) => setActionError(cause instanceof Error ? cause.message : 'Unable to delete the habit.')); }} /></View></AppModal>
    <AppModal visible={Boolean(eventActions)} onClose={() => { if (saving) return; setEventError(null); setEventActions(null); }}><View style={styles.modal}><Text style={[styles.modalTitle, { color: colors.text }]}>{eventActions?.title ?? 'Event options'}</Text>{eventActions && <Text style={{ color: colors.textMuted }}>{formatEventTime(eventActions.start, eventActions.end, eventActions.isAllDay)}</Text>}{eventError && <Text style={{ color: colors.danger }}>{eventError}</Text>}<Button label="Edit" variant="secondary" onPress={() => openEventEditor(eventActions)} /><Button label="Delete from Google Calendar" variant="danger" loading={saving} onPress={() => void removeEvent(eventActions)} /></View></AppModal>
    <AppModal visible={eventModal} onClose={() => { if (saving) return; setEventError(null); setEditingEvent(null); setEventModal(false); }}><View style={styles.modal}><Text style={[styles.modalTitle, { color: colors.text }]}>{editingEvent ? 'Edit calendar event' : 'New calendar event'}</Text><Text style={{ color: colors.textMuted }}>{fromDateKey(selected).toLocaleDateString()}</Text><FormInput accessibilityLabel="Event title" value={eventTitle} onChangeText={setEventTitle} placeholder="Event title" autoFocus /><View style={styles.timeRow}><View style={styles.timeInput}><FormInput accessibilityLabel="Start time" value={startTime} onChangeText={setStartTime} placeholder="09:00" keyboardType="numbers-and-punctuation" maxLength={5} /></View><View style={styles.timeInput}><FormInput accessibilityLabel="End time" value={endTime} onChangeText={setEndTime} placeholder="10:00" keyboardType="numbers-and-punctuation" maxLength={5} /></View></View>{!connected && <View style={[styles.connectNotice, { backgroundColor: colors.accentSoft, borderColor: colors.border }]}><Text style={[styles.connectNoticeTitle, { color: colors.text }]}>Connect Google Calendar to save this event</Text><Text style={[styles.connectNoticeText, { color: colors.textMuted }]}>Your event details will stay here while you authorize access.</Text>{calendar.error && <Text style={{ color: colors.danger }}>{calendar.error}</Text>}</View>}{eventError && <Text style={{ color: colors.danger }}>{eventError}</Text>}{connected ? <Button label={editingEvent ? 'Save changes' : 'Create event'} loading={saving} onPress={() => void saveEvent()} /> : <Button label="Connect to save" loading={calendar.loading} onPress={() => void calendar.connect()} />}</View></AppModal>
  </Screen>;
}

const styles = StyleSheet.create({ screen: { paddingTop: 18, paddingBottom: 108, gap: 14 }, titleRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, title: { fontSize: 29, fontWeight: '800' }, subtitle: { marginTop: 3, fontSize: 13 }, iconButton: { width: 42, height: 42, borderRadius: 16, alignItems: 'center', justifyContent: 'center' }, segment: { height: 45, borderWidth: StyleSheet.hairlineWidth, borderRadius: 17, padding: 3, flexDirection: 'row', overflow: 'hidden' }, segmentButton: { flex: 1, borderRadius: 14, alignItems: 'center', justifyContent: 'center' }, segmentText: { fontSize: 12, fontWeight: '700' }, connect: { borderWidth: StyleSheet.hairlineWidth, borderRadius: 26, padding: 14, gap: 9, overflow: 'hidden' }, box: { borderWidth: StyleSheet.hairlineWidth, borderRadius: 26, padding: 14, gap: 9, overflow: 'hidden' }, boxHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10 }, boxTitle: { fontSize: 18, fontWeight: '700' }, boxMeta: { fontSize: 11, marginTop: 2 }, eventList: { maxHeight: 260 }, item: { borderRadius: 16, padding: 11, marginBottom: 7, overflow: 'hidden' }, eventItem: { minHeight: 58, borderWidth: StyleSheet.hairlineWidth, borderLeftWidth: 3, flexDirection: 'row', alignItems: 'center', gap: 10 }, eventCopy: { flex: 1, minWidth: 0 }, eventHint: { fontSize: 10, fontWeight: '800' }, taskItem: { minHeight: 42, flexDirection: 'row', alignItems: 'center', gap: 9 }, priorityDot: { width: 7, height: 7, borderRadius: 4 }, itemTitle: { flex: 1, fontSize: 14, fontWeight: '700' }, itemMeta: { fontSize: 11, marginTop: 3 }, empty: { textAlign: 'center', paddingVertical: 22 }, dragSeed: { height: 38, borderRadius: 16, paddingHorizontal: 12, flexDirection: 'row', alignItems: 'center', gap: 7, zIndex: 5, overflow: 'hidden' }, dragText: { color: '#FFF', fontSize: 11, fontWeight: '700' }, timeSlots: { marginTop: 4 }, slot: { height: 38, borderTopWidth: StyleSheet.hairlineWidth, flexDirection: 'row', alignItems: 'center' }, slotTime: { width: 52, fontSize: 10 }, slotHint: { fontSize: 9 }, modal: { gap: 14 }, modalTitle: { fontSize: 22, fontWeight: '800' }, timeRow: { flexDirection: 'row', gap: 9 }, timeInput: { flex: 1 }, connectNotice: { borderWidth: StyleSheet.hairlineWidth, borderRadius: 18, padding: 11, gap: 4, overflow: 'hidden' }, connectNoticeTitle: { fontSize: 12, fontWeight: '800' }, connectNoticeText: { fontSize: 11, lineHeight: 16 } });
