import { BarChart3, Coffee, Pause, Play, Plus, StopCircle } from 'lucide-react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { AppState, ScrollView, StyleSheet, Text, View } from 'react-native';
import { DateSelector } from '@/components/tasks/DateSelector';
import { useFloatingTabBarMetrics } from '@/components/navigation/FloatingTabBar';
import { AppModal } from '@/components/ui/AppModal';
import { AnimatedPressable } from '@/components/ui/AnimatedPressable';
import { Button } from '@/components/ui/Button';
import { FormInput } from '@/components/ui/FormInput';
import { Screen } from '@/components/ui/Screen';
import { useAuth } from '@/contexts/AuthContext';
import { useTheme } from '@/contexts/ThemeContext';
import * as focusService from '@/services/focus';
import { readWidgetSnapshot, updateWidgetFocus } from '@/services/widgetSuite';
import type { BreakActivity, FocusBreak, FocusSession, FocusSubject } from '@/types/database';
import { toDateKey } from '@/utils/dates';

type ActiveTimer = { type: 'focus'; subject: FocusSubject; start: Date } | { type: 'break'; activity: BreakActivity; note: string | null; start: Date };
const activities: { value: BreakActivity; label: string }[] = [{ value: 'stare_at_wall', label: 'Stare at wall' }, { value: 'sports', label: 'Sports' }, { value: 'socialize', label: 'Socialize' }, { value: 'snacks', label: 'Snacks' }, { value: 'washroom', label: 'Washroom' }, { value: 'other', label: 'Other' }];
const formatDuration = (seconds: number) => seconds >= 3600 ? `${Math.floor(seconds / 3600)}h ${Math.floor((seconds % 3600) / 60)}m` : `${Math.floor(seconds / 60)}m ${seconds % 60}s`;

export default function FocusScreen() {
  const { startSubjectId } = useLocalSearchParams<{ startSubjectId?: string }>();
  const consumedWidgetSubject = useRef<string | null>(null);
  const { actionBottom: bottomActionsOffset } = useFloatingTabBarMetrics();
  const { colors } = useTheme(); const router = useRouter(); const { user } = useAuth(); const [date, setDate] = useState(toDateKey(new Date())); const [subjects, setSubjects] = useState<FocusSubject[]>([]); const [sessions, setSessions] = useState<FocusSession[]>([]); const [todaySeconds, setTodaySeconds] = useState(0); const [breaks, setBreaks] = useState<FocusBreak[]>([]); const [active, setActive] = useState<ActiveTimer | null>(null); const [elapsed, setElapsed] = useState(0); const [subjectModal, setSubjectModal] = useState(false); const [subjectName, setSubjectName] = useState(''); const [subjectToDelete, setSubjectToDelete] = useState<FocusSubject | null>(null); const [deletingSubject, setDeletingSubject] = useState(false); const [breakModal, setBreakModal] = useState(false); const [selectedActivity, setSelectedActivity] = useState<BreakActivity>('stare_at_wall'); const [customNote, setCustomNote] = useState(''); const [summaryOpen, setSummaryOpen] = useState(false); const [error, setError] = useState<string | null>(null);
  const loadDay = useCallback(async () => { if (!user) return; try { const [nextSessions, nextBreaks] = await Promise.all([focusService.listSessions(user.id, date), focusService.listBreaks(user.id, date)]); setSessions(nextSessions); setBreaks(nextBreaks); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to load focus history.'); } }, [user, date]);
  useEffect(() => { if (!user) return; void focusService.listSubjects(user.id).then(setSubjects).catch(() => setError('Run migration #2 to enable focus tracking.')); }, [user]);
  useEffect(() => {
    if (!startSubjectId || consumedWidgetSubject.current === startSubjectId || active) return;
    const subject = subjects.find((item) => item.id === startSubjectId);
    if (!subject) return;
    consumedWidgetSubject.current = startSubjectId;
    const start = new Date();
    setActive({ type: 'focus', subject, start });
    void updateWidgetFocus({ mode: 'focus', subjectId: subject.id, subjectName: subject.name, startedAt: start.getTime() / 1000, accumulatedSeconds: 0 });
  }, [active, startSubjectId, subjects]);
  useEffect(() => {
    const hydrate = async () => {
      const shared = await readWidgetSnapshot();
      if (!shared) return;
      if (shared.focus.mode === 'focus' && shared.focus.subjectId && shared.focus.startedAt) {
        const subject = subjects.find((item) => item.id === shared.focus.subjectId);
        if (subject) setActive({ type: 'focus', subject, start: new Date(shared.focus.startedAt * 1000) });
      } else if (shared.focus.mode === 'break' && shared.focus.startedAt) {
        setActive({ type: 'break', activity: 'other', note: null, start: new Date(shared.focus.startedAt * 1000) });
      } else if (shared.focus.mode === 'paused' || shared.focus.mode === 'idle') {
        setActive(null);
      }
    };
    if (subjects.length) void hydrate();
    const subscription = AppState.addEventListener('change', (state) => { if (state === 'active') void hydrate(); });
    return () => subscription.remove();
  }, [subjects]);
  useEffect(() => { void loadDay(); }, [loadDay]);
  useEffect(() => { if (!user) return; const today = toDateKey(new Date()); if (date === today) { setTodaySeconds(sessions.reduce((sum, session) => sum + session.duration_seconds, 0)); return; } void focusService.listSessions(user.id, today).then((items) => setTodaySeconds(items.reduce((sum, session) => sum + session.duration_seconds, 0))); }, [user, date, sessions]);
  useEffect(() => { if (!active) { setElapsed(0); return; } const update = () => setElapsed(Math.floor((Date.now() - active.start.getTime()) / 1000)); update(); const interval = setInterval(update, 1000); return () => clearInterval(interval); }, [active]);
  const total = todaySeconds + (active?.type === 'focus' ? elapsed : 0);
  const stop = async () => { if (!active || !user) return; const end = new Date(); try { if (active.type === 'focus') await focusService.saveSession(user.id, active.subject.id, active.start, end); else await focusService.saveBreak(user.id, active.activity, active.note, active.start, end); setActive(null); await updateWidgetFocus({ mode: 'idle', accumulatedSeconds: 0 }); await loadDay(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to save timer.'); } };
  const removeSubject = async () => { if (!user || !subjectToDelete) return; setDeletingSubject(true); setError(null); try { await focusService.deleteSubject(user.id, subjectToDelete.id); setSubjects((current) => current.filter((subject) => subject.id !== subjectToDelete.id)); setSessions((current) => current.filter((session) => session.subject_id !== subjectToDelete.id)); if (active?.type === 'focus' && active.subject.id === subjectToDelete.id) setActive(null); setSubjectToDelete(null); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to delete subject.'); } finally { setDeletingSubject(false); } };
  const timeline = useMemo(() => [...sessions.map((item) => ({ id: item.id, time: item.start_time, title: subjects.find((subject) => subject.id === item.subject_id)?.name ?? 'Focus', duration: item.duration_seconds, kind: 'Focus' })), ...breaks.map((item) => ({ id: item.id, time: item.start_time, title: item.activity_type === 'other' ? item.custom_note || 'Other' : activities.find((activity) => activity.value === item.activity_type)?.label ?? item.activity_type, duration: item.duration_seconds, kind: 'Break' }))].sort((a, b) => a.time.localeCompare(b.time)), [sessions, breaks, subjects]);
  return <Screen contentStyle={styles.screen}><View style={styles.hero}><Text style={[styles.eyebrow, { color: colors.textMuted }]}>TODAY’S TOTAL FOCUS</Text><Text style={[styles.total, { color: colors.text }]}>{formatDuration(total)}</Text><Text style={[styles.heroCaption, { color: colors.textMuted }]}>deep work completed</Text></View><DateSelector selected={date} onSelect={setDate} scrollable />
    {active && <View style={[styles.active, { backgroundColor: colors.accentSoft, borderColor: colors.accent }]}><View><Text style={[styles.activeLabel, { color: colors.text }]}>{active.type === 'focus' ? active.subject.name : 'Break'}</Text><Text style={[styles.stopwatch, { color: colors.accent }]}>{formatDuration(elapsed)}</Text></View><AnimatedPressable accessibilityLabel="Stop timer" onPress={() => void stop()} style={[styles.stop, { backgroundColor: colors.danger }]}><StopCircle color="#FFF" /></AnimatedPressable></View>}
    <View style={styles.actions}><Button label="Take a Break" icon={Coffee} variant="secondary" disabled={Boolean(active) || date !== toDateKey(new Date())} onPress={() => setBreakModal(true)} style={styles.action} /></View>
    {error && <Text style={{ color: colors.danger }}>{error}</Text>}
    <ScrollView style={styles.list} contentContainerStyle={styles.listContent}>{subjects.map((subject) => { const subjectTotal = sessions.filter((session) => session.subject_id === subject.id).reduce((sum, session) => sum + session.duration_seconds, 0) + (active?.type === 'focus' && active.subject.id === subject.id ? elapsed : 0); const running = active?.type === 'focus' && active.subject.id === subject.id; return <AnimatedPressable key={subject.id} accessibilityHint="Long press for subject options" onLongPress={() => setSubjectToDelete(subject)} delayLongPress={400} style={[styles.subject, { backgroundColor: colors.card, borderColor: running ? colors.accent : colors.border }]}><View style={styles.subjectCopy}><Text style={[styles.subjectName, { color: colors.text }]}>{subject.name}</Text><Text style={[styles.subjectTime, { color: colors.textMuted }]}>{formatDuration(subjectTotal)} {date === toDateKey(new Date()) ? 'today' : 'on selected day'}</Text></View><AnimatedPressable accessibilityLabel={running ? `Stop ${subject.name}` : `Start ${subject.name}`} disabled={Boolean(active) && !running || date !== toDateKey(new Date())} onPress={() => { if (running) { void stop(); return; } const start = new Date(); setActive({ type: 'focus', subject, start }); void updateWidgetFocus({ mode: 'focus', subjectId: subject.id, subjectName: subject.name, startedAt: start.getTime() / 1000, accumulatedSeconds: 0 }); }} style={[styles.play, { backgroundColor: running ? colors.danger : colors.accent, opacity: Boolean(active) && !running ? 0.4 : 1 }]}>{running ? <Pause color="#FFF" /> : <Play color={colors.buttonText} fill={colors.buttonText} />}</AnimatedPressable></AnimatedPressable>; })}{subjects.length === 0 && <Text style={[styles.empty, { color: colors.textMuted }]}>Add a subject to begin tracking focused work.</Text>}</ScrollView>
    <View pointerEvents="box-none" style={[styles.bottomActions, { bottom: bottomActionsOffset }]}>
      <AnimatedPressable accessibilityLabel="Open focus analytics" accessibilityRole="button" hitSlop={10} onPress={() => router.push('/focus-analytics')} style={[styles.analyticsFab, { backgroundColor: colors.card, borderColor: colors.border }]}><BarChart3 size={24} color={colors.accent} /></AnimatedPressable>
      <Button label="View day summary" variant="secondary" onPress={() => setSummaryOpen(true)} style={{ width: '69%', height: 52, flexShrink: 1, marginHorizontal: 6 }} />
      <AnimatedPressable accessibilityLabel="Add focus subject" onPress={() => setSubjectModal(true)} style={[styles.fab, { backgroundColor: colors.accent }]}><Plus size={25} color={colors.buttonText} /></AnimatedPressable>
    </View>
    <AppModal visible={subjectModal} onClose={() => setSubjectModal(false)}><View style={styles.modal}><Text style={[styles.modalTitle, { color: colors.text }]}>New subject</Text><FormInput accessibilityLabel="Subject name" value={subjectName} onChangeText={setSubjectName} placeholder="Mathematics, Writing…" autoFocus /><Button label="Add subject" disabled={!subjectName.trim()} onPress={() => { if (!user) return; void focusService.addSubject(user.id, subjectName.trim()).then((item) => { setSubjects((current) => [...current, item]); setSubjectName(''); setSubjectModal(false); }).catch((cause) => setError(cause.message)); }} /></View></AppModal>
    <AppModal visible={Boolean(subjectToDelete)} onClose={() => setSubjectToDelete(null)}><View style={styles.modal}><Text style={[styles.modalTitle, { color: colors.text }]}>Subject options</Text><Text style={{ color: colors.textMuted }}>Delete “{subjectToDelete?.name}” and its focus sessions?</Text><View style={styles.modalActions}><Button label="Cancel" variant="secondary" disabled={deletingSubject} onPress={() => setSubjectToDelete(null)} style={styles.modalAction} /><Button label="Delete Subject" variant="danger" loading={deletingSubject} onPress={() => void removeSubject()} style={styles.modalAction} /></View></View></AppModal>
    <AppModal visible={breakModal} onClose={() => setBreakModal(false)}><View style={styles.modal}><Text style={[styles.modalTitle, { color: colors.text }]}>Choose a break</Text><View style={styles.activityGrid}>{activities.map((activity) => <Text key={activity.value} onPress={() => setSelectedActivity(activity.value)} style={[styles.activity, { color: selectedActivity === activity.value ? colors.buttonText : colors.text, backgroundColor: selectedActivity === activity.value ? colors.accent : colors.card, borderColor: colors.border }]}>{activity.label}</Text>)}</View>{selectedActivity === 'other' && <FormInput accessibilityLabel="Break activity" value={customNote} onChangeText={setCustomNote} placeholder="What are you doing?" />}<Button label="Start break" disabled={selectedActivity === 'other' && !customNote.trim()} onPress={() => { const start = new Date(); setActive({ type: 'break', activity: selectedActivity, note: customNote.trim() || null, start }); void updateWidgetFocus({ mode: 'break', startedAt: start.getTime() / 1000, accumulatedSeconds: 0 }); setBreakModal(false); }} /></View></AppModal>
    <AppModal visible={summaryOpen} onClose={() => setSummaryOpen(false)}><View style={styles.modal}><Text style={[styles.modalTitle, { color: colors.text }]}>Day timeline</Text><ScrollView style={styles.timeline}>{timeline.length === 0 && <Text style={{ color: colors.textMuted }}>No sessions or breaks recorded.</Text>}{timeline.map((item) => <View key={`${item.kind}-${item.id}`} style={[styles.timelineItem, { borderBottomColor: colors.border }]}><Text style={[styles.timelineTime, { color: colors.textMuted }]}>{new Date(item.time).toLocaleTimeString(undefined, { hour: 'numeric', minute: '2-digit' })}</Text><View style={styles.timelineCopy}><Text style={[styles.timelineTitle, { color: colors.text }]}>{item.title}</Text><Text style={{ color: colors.textMuted, fontSize: 11 }}>{item.kind}</Text></View><Text style={{ color: colors.accent, fontWeight: '800' }}>{formatDuration(item.duration)}</Text></View>)}</ScrollView></View></AppModal>
  </Screen>;
}

const styles = StyleSheet.create({ screen: { paddingTop: 14, paddingBottom: 100, gap: 12 }, hero: { alignItems: 'center', paddingVertical: 8 }, eyebrow: { fontSize: 10, fontWeight: '800', letterSpacing: 1.4 }, total: { fontSize: 49, lineHeight: 58, fontWeight: '800', letterSpacing: -1.5 }, heroCaption: { fontSize: 11 }, active: { minHeight: 72, borderRadius: 18, borderWidth: StyleSheet.hairlineWidth, padding: 14, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, activeLabel: { fontSize: 15, fontWeight: '700' }, stopwatch: { fontSize: 22, fontWeight: '800', marginTop: 3 }, stop: { width: 46, height: 46, borderRadius: 15, alignItems: 'center', justifyContent: 'center' }, actions: { flexDirection: 'row', gap: 8 }, action: { flex: 1 }, list: { flex: 1 }, listContent: { gap: 7 }, subject: { minHeight: 64, borderRadius: 17, borderWidth: StyleSheet.hairlineWidth, padding: 12, flexDirection: 'row', alignItems: 'center' }, subjectCopy: { flex: 1 }, subjectName: { fontSize: 16, fontWeight: '700' }, subjectTime: { fontSize: 11, marginTop: 3 }, play: { width: 43, height: 43, borderRadius: 14, alignItems: 'center', justifyContent: 'center' }, empty: { textAlign: 'center', paddingVertical: 42 }, modal: { gap: 15 }, modalTitle: { fontSize: 22, fontWeight: '800' }, modalActions: { flexDirection: 'row', gap: 9 }, modalAction: { flex: 1 }, activityGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 }, activity: { borderWidth: StyleSheet.hairlineWidth, borderRadius: 13, paddingHorizontal: 12, paddingVertical: 9, fontWeight: '700', overflow: 'hidden' }, timeline: { maxHeight: 440 }, timelineItem: { minHeight: 60, borderBottomWidth: StyleSheet.hairlineWidth, flexDirection: 'row', alignItems: 'center', gap: 10 }, timelineTime: { width: 66, fontSize: 11 }, timelineCopy: { flex: 1 }, timelineTitle: { fontWeight: '700' }, bottomActions: { position: 'absolute', left: 14, right: 14, height: 52, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', zIndex: 2 }, analyticsFab: { width: 52, height: 52, borderRadius: 26, borderWidth: StyleSheet.hairlineWidth, alignItems: 'center', justifyContent: 'center', shadowColor: '#000', shadowOpacity: 0.1, shadowRadius: 10, shadowOffset: { width: 0, height: 5 }, elevation: 4 }, fab: { width: 52, height: 52, borderRadius: 26, alignItems: 'center', justifyContent: 'center', shadowColor: '#000', shadowOpacity: 0.2, shadowRadius: 12, shadowOffset: { width: 0, height: 6 }, elevation: 6 } });
