import { FolderInput, Pin, PinOff, RotateCcw, Trash2 } from 'lucide-react-native';
import { StyleSheet, Text, View } from 'react-native';
import { Swipeable } from 'react-native-gesture-handler';
import Animated, { FadeInDown, LinearTransition, useReducedMotion } from 'react-native-reanimated';
import { AnimatedPressable } from '@/components/ui/AnimatedPressable';
import { collapseOut } from '@/constants/animations';
import { motion } from '@/constants/theme';
import { useTheme } from '@/contexts/ThemeContext';
import type { ChecklistItem, Note } from '@/types/database';

const plain = (value: string) => value.replace(/<[^>]+>/g, ' ').replace(/&nbsp;/g, ' ').replace(/\s+/g, ' ').trim();
function checklist(value: Note['checklist_data']) { return Array.isArray(value) ? value as unknown as ChecklistItem[] : []; }

export function NoteCard({ note, grid, deleted, onOpen, onPin, onMove, onTrash, onRestore, index = 0 }: { note: Note; grid: boolean; deleted?: boolean; onOpen: () => void; onPin: () => void; onMove: () => void; onTrash: () => void; onRestore: () => void; index?: number }) {
  const { colors } = useTheme(); const reduceMotion = useReducedMotion(); const checks = checklist(note.checklist_data); const preview = plain(note.content || note.content_html);
  const left = () => deleted ? <AnimatedPressable onPress={onRestore} style={[styles.action, { backgroundColor: colors.success }]}><RotateCcw color="#FFF" size={18} /><Text style={styles.actionText}>Restore</Text></AnimatedPressable> : <AnimatedPressable onPress={onPin} style={[styles.action, { backgroundColor: colors.notesAccent }]}>{note.is_pinned ? <PinOff color="#000" size={18} /> : <Pin color="#000" size={18} />}<Text style={[styles.actionText, { color: '#000' }]}>{note.is_pinned ? 'Unpin' : 'Pin'}</Text></AnimatedPressable>;
  const right = () => <View style={styles.actions}>{!deleted && <AnimatedPressable onPress={onMove} style={[styles.action, { backgroundColor: '#5E5CE6' }]}><FolderInput color="#FFF" size={18} /><Text style={styles.actionText}>Move</Text></AnimatedPressable>}<AnimatedPressable onPress={onTrash} style={[styles.action, { backgroundColor: colors.danger }]}><Trash2 color="#FFF" size={18} /><Text style={styles.actionText}>{deleted ? 'Delete' : 'Trash'}</Text></AnimatedPressable></View>;
  return <Animated.View entering={reduceMotion ? undefined : FadeInDown.delay(Math.min(index, 10) * motion.stagger).duration(260)} exiting={reduceMotion ? undefined : collapseOut} layout={reduceMotion ? undefined : LinearTransition.springify().damping(18)} style={grid && styles.gridWrap}><Swipeable overshootLeft={false} overshootRight={false} renderLeftActions={left} renderRightActions={right}><AnimatedPressable onPress={onOpen} style={[styles.card, grid && styles.grid, { backgroundColor: colors.card, borderColor: colors.border }]}><View style={styles.titleRow}>{note.is_pinned && <Pin size={12} fill={colors.notesAccent} color={colors.notesAccent} />}<Text numberOfLines={1} style={[styles.title, { color: colors.text }]}>{note.title || 'New Note'}</Text></View><Text numberOfLines={grid ? 5 : 2} style={[styles.preview, { color: colors.textMuted }]}>{preview || (checks.length ? `${checks.filter((item) => item.isCompleted).length} of ${checks.length} checklist items` : 'No additional text')}</Text>{checks.slice(0, grid ? 3 : 1).map((item) => <View key={item.id} style={styles.check}><View style={[styles.checkDot, { borderColor: colors.notesAccent, backgroundColor: item.isCompleted ? colors.notesAccent : 'transparent' }]} /><Text numberOfLines={1} style={[styles.checkText, { color: colors.textMuted, textDecorationLine: item.isCompleted ? 'line-through' : 'none' }]}>{item.text}</Text></View>)}<Text style={[styles.date, { color: colors.textMuted }]}>{new Date(note.updated_at).toLocaleDateString(undefined, { day: 'numeric', month: 'short' })}</Text></AnimatedPressable></Swipeable></Animated.View>;
}

const styles = StyleSheet.create({ gridWrap: { width: '48.5%' }, card: { minHeight: 76, borderBottomWidth: StyleSheet.hairlineWidth, paddingVertical: 11, paddingHorizontal: 12 }, grid: { minHeight: 150, borderWidth: StyleSheet.hairlineWidth, borderRadius: 17, padding: 13 }, titleRow: { flexDirection: 'row', alignItems: 'center', gap: 5 }, title: { flex: 1, fontSize: 15, fontWeight: '700' }, preview: { fontSize: 11, lineHeight: 16, marginTop: 4 }, date: { fontSize: 9, marginTop: 7 }, check: { flexDirection: 'row', alignItems: 'center', gap: 5, marginTop: 5 }, checkDot: { width: 10, height: 10, borderRadius: 5, borderWidth: 1 }, checkText: { flex: 1, fontSize: 9 }, actions: { flexDirection: 'row' }, action: { width: 72, alignItems: 'center', justifyContent: 'center', gap: 4 }, actionText: { color: '#FFF', fontSize: 10, fontWeight: '700' } });
