import { useRef } from 'react';
import { StyleProp, StyleSheet, Text, View, ViewStyle } from 'react-native';
import { actions, RichEditor, RichToolbar } from 'react-native-pell-rich-editor';
import { AnimatedPressable } from '@/components/ui/AnimatedPressable';
import { useTheme } from '@/contexts/ThemeContext';

export function RichTextEditor({ value, onChange, minHeight = 180, style }: { value: string; onChange: (html: string) => void; minHeight?: number; style?: StyleProp<ViewStyle> }) {
  const { colors } = useTheme(); const editor = useRef<RichEditor>(null);
  return <View style={[styles.shell, { borderColor: colors.border }, style]}><RichToolbar editor={editor} actions={[actions.setBold, actions.setItalic, actions.setUnderline, actions.heading1, actions.heading2, actions.setParagraph, actions.insertBulletsList, actions.insertOrderedList, actions.undo, actions.redo]} selectedIconTint={colors.accent} iconTint={colors.textMuted} style={{ backgroundColor: colors.cardElevated }} /><View style={[styles.customBar, { backgroundColor: colors.cardElevated, borderTopColor: colors.border }]}><AnimatedPressable onPress={() => editor.current?.setFontSize(2)}><Text style={[styles.tool, { color: colors.text }]}>Small</Text></AnimatedPressable><AnimatedPressable onPress={() => editor.current?.setFontSize(4)}><Text style={[styles.tool, { color: colors.text }]}>Body</Text></AnimatedPressable><AnimatedPressable onPress={() => editor.current?.setFontSize(6)}><Text style={[styles.tool, { color: colors.text }]}>Large</Text></AnimatedPressable>{['#FFF176','#80DEEA','#F48FB1'].map((color) => <AnimatedPressable key={color} accessibilityLabel={`Highlight ${color}`} onPress={() => editor.current?.setHiliteColor(color)} style={[styles.swatch, { backgroundColor: color }]} />)}</View><RichEditor ref={editor} style={styles.editor} initialContentHTML={value} onChange={onChange} initialHeight={minHeight} placeholder="Start writing…" editorStyle={{ backgroundColor: colors.card, color: colors.text, caretColor: colors.accent, placeholderColor: colors.textMuted, contentCSSText: 'font-family: -apple-system, system-ui; font-size: 16px; line-height: 1.55;' }} /></View>;
}
const styles = StyleSheet.create({ shell: { flex: 1, borderWidth: StyleSheet.hairlineWidth, borderRadius: 16, overflow: 'hidden' }, editor: { flex: 1 }, customBar: { minHeight: 36, borderTopWidth: StyleSheet.hairlineWidth, flexDirection: 'row', alignItems: 'center', gap: 12, paddingHorizontal: 10 }, tool: { fontSize: 11, fontWeight: '800' }, swatch: { width: 20, height: 20, borderRadius: 6 } });
