import { MapPin, Sparkles, X } from 'lucide-react-native';
import { useEffect, useState } from 'react';
import { ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { AttachmentBar } from '@/components/shared/AttachmentBar';
import { AnimatedPressable } from '@/components/ui/AnimatedPressable';
import { AppModal } from '@/components/ui/AppModal';
import { Button } from '@/components/ui/Button';
import { FormInput } from '@/components/ui/FormInput';
import { useTheme } from '@/contexts/ThemeContext';
import type { JournalEntry, JournalLocation } from '@/types/database';
import type { JournalDraft } from '@/services/journal';
import { toDateKey } from '@/utils/dates';

const prompts = ['What felt meaningful today?', 'What challenged you?', 'What do you want to remember?'];
export function JournalComposer({ visible, entry, initialPrompt, onClose, onSave, onUpload }: { visible: boolean; entry: JournalEntry | null; initialPrompt?: { category: string; prompt: string } | null; onClose: () => void; onSave: (draft: JournalDraft) => Promise<void>; onUpload: (file: { uri: string; mimeType: string; fileName: string; kind: 'image' | 'video' | 'audio' }) => Promise<{ url: string; kind: 'image' | 'video' | 'audio' }> }) {
  const { colors } = useTheme(); const [title, setTitle] = useState(''); const [body, setBody] = useState(''); const [date, setDate] = useState(toDateKey(new Date())); const [media, setMedia] = useState<string[]>([]); const [voice, setVoice] = useState<string | null>(null); const [location, setLocation] = useState(''); const [promptCategory, setPromptCategory] = useState<string | null>(null); const [mood, setMood] = useState(''); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);
  useEffect(() => { if (!visible) return; const currentLocation = entry?.location as unknown as JournalLocation | null; setTitle(entry?.title ?? ''); setBody(entry?.body_text ?? initialPrompt?.prompt ?? ''); setDate(entry?.date_string ?? toDateKey(new Date())); setMedia(entry?.media_urls ?? []); setVoice(entry?.voice_memo_url ?? null); setLocation(currentLocation?.name ?? ''); setPromptCategory(entry?.prompt_category ?? initialPrompt?.category ?? null); setMood(entry?.mood ?? ''); setError(null); }, [visible, entry, initialPrompt]);
  const save = async () => { if (!title.trim() && !body.trim()) { setError('Write a title or reflection first.'); return; } setSaving(true); try { await onSave({ id: entry?.id, date, title: title.trim(), bodyText: body, mediaUrls: media, voiceMemoUrl: voice, location: location.trim() ? { name: location.trim() } : null, promptCategory, mood: mood.trim() || null }); onClose(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to save entry.'); } finally { setSaving(false); } };
  return <AppModal visible={visible} onClose={onClose} sheetStyle={styles.sheet}><View style={styles.composer}><View style={styles.header}><AnimatedPressable onPress={onClose} accessibilityLabel="Close journal composer"><X color={colors.textMuted} /></AnimatedPressable><Text style={[styles.heading, { color: colors.text }]}>{entry ? 'Edit Entry' : 'New Entry'}</Text><Button label="Save" loading={saving} onPress={() => void save()} style={styles.save} /></View><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={styles.content}><FormInput accessibilityLabel="Journal date" value={date} onChangeText={setDate} placeholder="YYYY-MM-DD" /><TextInput value={title} onChangeText={setTitle} placeholder="A title for this moment" placeholderTextColor={colors.textMuted} style={[styles.title, { color: colors.text }]} /><TextInput value={body} onChangeText={setBody} placeholder="Start writing…" placeholderTextColor={colors.textMuted} multiline textAlignVertical="top" style={[styles.body, { color: colors.text }]} /><View style={styles.promptRow}><Sparkles size={15} color={colors.journalAccent} />{prompts.map((prompt) => <AnimatedPressable key={prompt} onPress={() => setBody((value) => value || prompt)} style={[styles.prompt, { borderColor: colors.border }]}><Text numberOfLines={1} style={[styles.promptText, { color: colors.textMuted }]}>{prompt}</Text></AnimatedPressable>)}</View><View style={styles.fields}><View style={styles.field}><MapPin size={16} color={colors.journalAccent} /><TextInput value={location} onChangeText={setLocation} placeholder="Add location" placeholderTextColor={colors.textMuted} style={[styles.inlineInput, { color: colors.text }]} /></View><FormInput accessibilityLabel="Mood" value={mood} onChangeText={setMood} placeholder="Mood · calm, happy, reflective…" /></View><AttachmentBar onAttachment={async (file) => { const upload = await onUpload(file); if (upload.kind === 'image') setMedia((current) => [...current, upload.url]); else setVoice(upload.url); }} />{(media.length > 0 || voice) && <Text style={[styles.attachments, { color: colors.textMuted }]}>{media.length} photos{voice ? ' · 1 voice memo' : ''}</Text>}{error && <Text style={{ color: colors.danger }}>{error}</Text>}</ScrollView></View></AppModal>;
}
const styles = StyleSheet.create({ sheet: { height: '92%' }, composer: { flex: 1 }, header: { minHeight: 58, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, heading: { fontSize: 16, fontWeight: '700' }, save: { minHeight: 36, paddingHorizontal: 13 }, content: { paddingVertical: 12, gap: 13 }, title: { fontSize: 27, fontWeight: '700', paddingVertical: 6 }, body: { minHeight: 240, fontSize: 16, lineHeight: 24 }, promptRow: { flexDirection: 'row', alignItems: 'center', gap: 7 }, prompt: { maxWidth: 150, borderWidth: StyleSheet.hairlineWidth, borderRadius: 14, paddingHorizontal: 10, paddingVertical: 7 }, promptText: { fontSize: 9 }, fields: { gap: 9 }, field: { minHeight: 48, flexDirection: 'row', alignItems: 'center', gap: 8 }, inlineInput: { flex: 1, fontSize: 14 }, attachments: { fontSize: 11 } });
