import { BlurView } from 'expo-blur';
import { Bookmark, MapPin, Mic, Trash2 } from 'lucide-react-native';
import { StyleSheet, Text, View } from 'react-native';
import Animated, { FadeInDown, LinearTransition, useReducedMotion } from 'react-native-reanimated';
import { MediaGrid } from '@/components/journal/MediaGrid';
import { AnimatedPressable } from '@/components/ui/AnimatedPressable';
import { collapseOut } from '@/constants/animations';
import { motion } from '@/constants/theme';
import { useTheme } from '@/contexts/ThemeContext';
import type { JournalEntry, JournalLocation } from '@/types/database';

export function JournalCard({ entry, onOpen, onBookmark, onDelete, index = 0 }: { entry: JournalEntry; onOpen: () => void; onBookmark: () => void; onDelete: () => void; index?: number }) {
  const { colors, theme } = useTheme(); const reduceMotion = useReducedMotion(); const location = entry.location as unknown as JournalLocation | null;
  return <Animated.View entering={reduceMotion ? undefined : FadeInDown.delay(Math.min(index, 10) * motion.stagger).duration(270)} exiting={reduceMotion ? undefined : collapseOut} layout={reduceMotion ? undefined : LinearTransition.springify().damping(18)}><AnimatedPressable onPress={onOpen} style={[styles.shell, { borderColor: colors.border, shadowColor: '#000' }]}><BlurView intensity={80} tint={theme === 'light' ? 'light' : 'dark'} style={[StyleSheet.absoluteFill, { backgroundColor: colors.glass }]} /><View style={styles.header}><View><Text style={[styles.time, { color: colors.journalAccent }]}>{new Date(entry.created_at).toLocaleTimeString(undefined, { hour: 'numeric', minute: '2-digit' })}{entry.mood ? ` · ${entry.mood}` : ''}</Text>{location?.name && <View style={styles.inline}><MapPin size={11} color={colors.textMuted} /><Text style={[styles.meta, { color: colors.textMuted }]}>{location.name}</Text></View>}</View><View style={styles.inline}><AnimatedPressable accessibilityLabel="Delete journal entry" onPress={onDelete} hitSlop={8}><Trash2 size={17} color={colors.textMuted} /></AnimatedPressable><AnimatedPressable accessibilityLabel={entry.is_bookmarked ? 'Remove bookmark' : 'Bookmark'} onPress={onBookmark} hitSlop={8}><Bookmark size={20} color={colors.journalAccent} fill={entry.is_bookmarked ? colors.journalAccent : 'transparent'} /></AnimatedPressable></View></View><Text style={[styles.title, { color: colors.text }]}>{entry.title || 'Untitled moment'}</Text><Text numberOfLines={4} style={[styles.body, { color: colors.textMuted }]}>{entry.body_text}</Text><MediaGrid urls={entry.media_urls} />{entry.voice_memo_url && <View style={[styles.voice, { backgroundColor: `${colors.journalAccent}20` }]}><Mic size={15} color={colors.journalAccent} /><Text style={[styles.voiceText, { color: colors.text }]}>Voice memo</Text></View>}</AnimatedPressable></Animated.View>;
}

const styles = StyleSheet.create({ shell: { borderWidth: StyleSheet.hairlineWidth, borderRadius: 22, padding: 16, overflow: 'hidden', shadowOpacity: 0.16, shadowRadius: 16, shadowOffset: { width: 0, height: 7 }, elevation: 4 }, header: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between' }, inline: { flexDirection: 'row', alignItems: 'center', gap: 5 }, time: { fontSize: 11, fontWeight: '700' }, meta: { fontSize: 10, marginTop: 2 }, title: { fontSize: 19, fontWeight: '700', marginTop: 12 }, body: { fontSize: 13, lineHeight: 19, marginTop: 5 }, voice: { minHeight: 42, borderRadius: 13, paddingHorizontal: 12, flexDirection: 'row', alignItems: 'center', gap: 7, marginTop: 10 }, voiceText: { fontSize: 11, fontWeight: '700' } });
