import { closestCenter, DndContext, DragEndEvent, PointerSensor, useDroppable, useSensor, useSensors } from '@dnd-kit/core';
import { CSS } from '@dnd-kit/utilities';
import { useSortable } from '@dnd-kit/sortable';
import { GripVertical } from 'lucide-react-native';
import { StyleSheet, Text, View } from 'react-native';
import { CompactTaskRow } from '@/components/tasks/CompactTaskRow';
import { AnimatedPressable } from '@/components/ui/AnimatedPressable';
import { priorityColors, priorityLabels } from '@/constants/theme';
import { useTheme } from '@/contexts/ThemeContext';
import type { TaskPriority, TaskWithSubtasks } from '@/types/database';

const priorities: TaskPriority[] = ['red', 'yellow', 'blue', 'green'];
const priorityRows: TaskPriority[][] = [priorities.slice(0, 2), priorities.slice(2, 4)];
function SortableTask({ task, onComplete, onRename }: { task: TaskWithSubtasks; onComplete: () => void; onRename: (title: string) => void | Promise<void> }) { const { attributes, listeners, setNodeRef, transform, transition, isDragging } = useSortable({ id: task.id, data: { priority: task.priority } }); const { colors } = useTheme(); const dragTransform = CSS.Transform.toString(transform); return <div ref={setNodeRef} style={{ transform: `${dragTransform ?? ''} ${isDragging ? 'scale(1.05) rotate(2deg)' : 'scale(1) rotate(0deg)'}`, transition, opacity: isDragging ? 0.96 : 1, position: 'relative', zIndex: isDragging ? 10 : 1, boxShadow: isDragging ? '0 18px 38px rgba(0,0,0,0.32)' : 'none' }}><CompactTaskRow task={task} onToggle={onComplete} onRename={onRename} showColorDot={false} showDate={false} dragHandle={<div {...attributes} {...listeners} style={{ padding: 6, cursor: 'grab' }}><GripVertical size={13} color={colors.textMuted} /></div>} /></div>; }
function Quadrant({ priority, tasks, onComplete, onRename, onOpen }: { priority: TaskPriority; tasks: TaskWithSubtasks[]; onComplete: (task: TaskWithSubtasks) => void; onRename: (task: TaskWithSubtasks, title: string) => void | Promise<void>; onOpen: () => void }) { const { colors } = useTheme(); const { setNodeRef, isOver } = useDroppable({ id: `quadrant-${priority}`, data: { priority } }); return <div ref={setNodeRef} style={{ flex: '1 1 0', minWidth: 0, height: '100%' }}><View style={[styles.quadrant, { backgroundColor: colors.card, borderColor: isOver ? priorityColors[priority] : colors.border }]}><AnimatedPressable accessibilityRole="button" accessibilityLabel={`Open ${priorityLabels[priority]} tasks`} onPress={onOpen} style={styles.header}><View style={[styles.dot, { backgroundColor: priorityColors[priority] }]} /><Text style={[styles.title, { color: colors.text }]}>{priorityLabels[priority]}</Text><Text style={[styles.count, { color: colors.textMuted }]}>{tasks.length}</Text></AnimatedPressable><div style={{ flex: '1 1 0', minHeight: 0, overflowY: 'auto' }}>{tasks.map((task) => <SortableTask key={task.id} task={task} onComplete={() => onComplete(task)} onRename={(title) => onRename(task, title)} />)}{tasks.length === 0 && <Text style={[styles.empty, { color: colors.textMuted }]}>Drop tasks here</Text>}</div></View></div>; }
export function MatrixBoard({ tasks, onComplete, onMove, onRename, onOpenQuadrant }: { tasks: TaskWithSubtasks[]; onComplete: (task: TaskWithSubtasks) => void; onMove: (task: TaskWithSubtasks, priority: TaskPriority) => void; onRename: (task: TaskWithSubtasks, title: string) => void | Promise<void>; onOpenQuadrant: (priority: TaskPriority) => void }) { const sensors = useSensors(useSensor(PointerSensor, { activationConstraint: { distance: 5 } })); const end = ({ active, over }: DragEndEvent) => { if (!over) return; const task = tasks.find((item) => item.id === active.id); const overTask = tasks.find((item) => item.id === over.id); const target = (over.data.current?.priority ?? overTask?.priority) as TaskPriority | undefined; if (task && target && target !== task.priority) onMove(task, target); }; return <DndContext sensors={sensors} collisionDetection={closestCenter} onDragEnd={end}><View style={styles.grid}>{priorityRows.map((row, rowIndex) => <View key={rowIndex} style={styles.row}>{row.map((priority) => <Quadrant key={priority} priority={priority} tasks={tasks.filter((task) => task.priority === priority)} onComplete={onComplete} onRename={onRename} onOpen={() => onOpenQuadrant(priority)} />)}</View>)}</View></DndContext>; }
const styles = StyleSheet.create({ grid: { flex: 1, gap: 8 }, row: { flex: 1, minHeight: 0, flexDirection: 'row', gap: 8 }, quadrant: { width: '100%', height: '100%', minHeight: 0, borderRadius: 16, borderWidth: StyleSheet.hairlineWidth, padding: 8 }, header: { minHeight: 20, flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: 4 }, dot: { width: 7, height: 7, borderRadius: 4 }, title: { flex: 1, fontSize: 10, fontWeight: '700' }, count: { fontSize: 9 }, empty: { textAlign: 'center', fontSize: 9, paddingVertical: 20 } });
